# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl -sSf -u "denis.lysyi@meduzzen.com:Meduzzen2022!"  -O 'https://testflasddd.jfrog.io/artifactory/generic-local/intel-ipsec-mb.tar'
    tar xvf  intel-ipsec-mb.tar
    ls
  displayName: 'Run a multi-line script'
